# application: ga-beacon
# version: 11
# runtime: go113
runtime: go
api_version: go1

default_expiration: "1d"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: auto
